# Generated by Django 5.2 on 2025-10-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_id_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryc',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
