# Generated by Django 5.2 on 2025-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_product_categoryc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryc',
            new_name='category',
        ),
    ]
